Wallet integration into starter app
eluv-io/elv-starter-app pull request #5
Opened 2022-06-28 20:46 UTC by elv-seth

2022-06-28 21:42 UTC, elv-wayne reviewed
Can you check if `npm run lint` gives no errors? I see a pre-commit key in the package.json but not sure if that's working.  Other than some indentation issues it's a good start.

2022-06-28 21:46 UTC, elv-kevin commented
I would prefer that we don't use / link to elv-components-js

Also, I'd recommend removing pre-commit

2022-06-28 21:49 UTC, elv-wayne commented
> 

We're using the media-apps branch of elv-components

2022-06-28 21:51 UTC, elv-zenia commented
@elv-kevin Have you run into issues with pre-commits?

2022-06-28 22:38 UTC, elv-seth commented
Just pushed a new commit addressing the issues I found with "npm run lint" and some formatting.

2022-06-28 23:18 UTC, elv-zenia requested changes
This is awesome, Seth. A few notes in addition to the comments I left. 

- When setting properties, don't use spaces in between equal signs and brackets, e.g., `src={}`.

- Stylesheets should go in src/static/stylesheets and should be .scss, not .css.
- Don't use inline styling. Keep it separate from JS in stylesheets.
- Be careful with extra lines. Use no more than one empty line if separating code blocks.
- You shouldn't need styled-components if using elv-components.
Lastly, can you try to implement a navbar from scratch instead of using Material?

2022-06-28 23:18 UTC, elv-zenia commented on src/components/GettingStarted.css
> +    color: white;
Always use color variables in css. Check out /elv-components-js/src/stylesheets/variables/colors.scss.

2022-06-28 23:18 UTC, elv-zenia commented on src/components/GettingStarted.js
> +
Move styling to a stylesheet. Also look into replacing PrimaryButton with an `Action` component from elv-components-js

2022-06-28 23:18 UTC, elv-zenia commented on src/components/Home.js
> +    </div>
Use React fragments https://reactjs.org/docs/fragments.html
```suggestion
    <>
      <div style = {{height: "100px"}}/>
      <p>Hello {name.split(" ")[0]},</p>
      <p>This project template uses and demonstrates the following Eluvio projects:</p>
      <a href = "https://github.com/eluv-io/elv-media-wallet" target="_blank"><p style =  {{color: "rgba(81,184,240,1)"}}>-elv-media-wallet</p></a>
      <a href = "https://github.com/eluv-io/elv-components-js" target="_blank"><p style = {{color: "rgba(81,184,240,1)"}}>-elv-components-js</p></a>
      <div style = {{height: "100px"}}/>
      <PrimaryButton onClick = {
        Logout
      }><p>Logout</p></PrimaryButton>
    </>
```

2022-06-28 23:18 UTC, elv-zenia commented on src/components/Home.js
> +      <a href = "https://github.com/eluv-io/elv-media-wallet" target="_blank"><p style =  {{color: "rgba(81,184,240,1)"}}>-elv-media-wallet</p></a>
Replace anchor tags with elv-components-js `<Link>`

2022-06-28 23:18 UTC, elv-zenia commented on src/router/index.js
> +
Remove extra lines. Check throughout your changes. There generally shouldn't be more than one consecutive empty line 
Will also look into adding a linting rule for this

2022-06-28 23:18 UTC, elv-zenia commented on src/router/index.js
> +  const [loggedIn,setLoggedIn] = useState(false);
Can you move `loggedIn` state to a data store? We don't have any set up yet but the structure should be src/stores/index.js (rootStore). Look at elv-music-js's rootStore and elv-media-wallet's rootStore

2022-06-30 17:46 UTC, elv-zenia requested changes
Left comments for minor things.
I see that you're using Flux, which I believe is integrated into Redux since I think they follow the paradigm of needing to dispatch values in order to update state. The difference with Mobx--and one of the advantages-- is that it serves as a data layer that automatically changes the UI layer to reflect any changes in state. So the idea is to set up the store so that it contains observables and actions, which mutate state. 

Like so
```
class RootStore {
  loggedIn = false;

  constructor() {
    makeAutoObservable(this);
  }

  Authenticate() {
    this.loggedIn = true;
  }
}
```

And then set up your component so that it imports the store and is an observer.

```
import {rootStore} from "Stores/index";

const SomeComponent = observer (() => {
  return (
    <div>{ rootStore.loggedIn }</div>
  );
});
```
So in the simple component above, the value of `loggedIn` will change every time the state changes in the store.
The Mobx ten-minute intro is a solid read on this: https://mobx.js.org/getting-started

And, of course, let me know if you want to talk about this more.

2022-06-30 17:46 UTC, elv-zenia commented on package.json
> +    "styled-components": "^5.3.5"
Can you remove @material-ui/core, material-ui, react-icons, and styled-components?

2022-06-30 17:46 UTC, elv-zenia commented on src/components/GettingStarted.js
> +        <Action label="login"title="Login"type="button"className="primarybtn"onClick={Login}children={<p className="btntext">Login</p>} />
Sorry, I think I added confusion about the spaces
```suggestion
        <Action label="login" title="Login" type="button" className="primarybtn" onClick={Login} children={<p className="btntext">Login</p>} />
```

2022-06-30 17:46 UTC, elv-zenia commented on src/components/Navbar.js
> +        <Link to="/" >Home</Link>
```suggestion
        <Link to="/">Home</Link>
```

2022-06-30 17:46 UTC, elv-zenia commented on src/index.js
> +
Extra lines

2022-07-01 21:23 UTC, elv-zenia approved these changes

2022-07-01 21:24 UTC, merged